citation_select.settings:
  type: config_object
  label: 'Module common configuration'
  mapping:
    default_style:
      type: string
    show_on_load:
      type: boolean
      label: 'Show Citation by default'
    reference_type_field_map:
      type: ignore
      label: 'Reference Type Field Map'
    csl_map:
      type: ignore
      label: 'CSL Map'
    typed_relation_map:
      type: ignore
      label: 'Typed Relation Map'